version: '2'
services:
    redis:
      image:  redis
    db:
      image: postgres:latest
      links:
        - ""
    webserver:
      image: nginx
      ports:
        - 8080:80
    links: 
        - redis 
